FROM almalinux/9-base
ADD cta-public-5-alma9.repo  /etc/yum.repos.d/

RUN dnf upgrade -y \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install 'dnf-command(config-manager)'\
    && dnf clean all \
    && rm -rf /var/cache/dnf
RUN dnf config-manager --set-enabled crb

RUN dnf install -y epel-release python python3-devel pip libpq-devel gcc unzip \
# Convenience stuff. Remove in production?
                   git which nano wget jq sudo procps \
    && dnf clean all \
    && rm -rf /var/cache/dnf

ADD cta-public-5-alma9.repo  /etc/yum.repos.d/
ADD oracle.repo  /etc/yum.repos.d/
RUN dnf -y install https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-basic-21.12.0.0.0-1.el9.x86_64.rpm
RUN dnf -y install cta-catalogueutils \
    && dnf clean all \
    && rm -rf /var/cache/yum

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
