FROM almalinux/9-base
ARG CTA_RELEASE=5.10.11.0-1.el9.el9
#ADD cta-public-5-alma9.repo  /etc/yum.repos.d/
ADD cta-public-5-test-alma9.repo  /etc/yum.repos.d/
ADD ceph.repo  /etc/yum.repos.d/

RUN dnf upgrade -y \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install 'dnf-command(config-manager)'\
    && dnf clean all \
    && rm -rf /var/cache/dnf
RUN dnf config-manager --set-enabled crb

RUN dnf -y install https://download.oracle.com/otn_software/linux/instantclient/2112000/el9/oracle-instantclient-basic-21.12.0.0.0-1.el9.x86_64.rpm

RUN dnf install -y epel-release procps-ng && \
    dnf install -y libpq-devel gcc \
                   xrootd-server cta-frontend-$CTA_RELEASE cta-frontend-grpc-$CTA_RELEASE \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf install -y cta-objectstore-tools-$CTA_RELEASE

RUN chmod 777 /var/log/cta
RUN mkdir /etc/cta-nobody/
RUN chmod 777 /etc/cta-nobody/

ADD entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
